name: rst_bootstrap
description: A bootstrap latest SCSS based bootstrap css framework
version: 4.2.1
author: David Zhao <david.zhao@resentek.com>
homepage: null

environment:
  sdk: '>=2.0.0 < 3.0.0'

dev_dependencies:
  build_runner: ^1.2.5
  build_web_compilers: ^1.1.0
  sass_builder: ^2.1.2